name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: super-flashcards-475210
  SERVICE_NAME: super-flashcards
  REGION: us-central1

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --quiet
      
      - name: Get Service URL
        id: get-url
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --format='value(status.url)')
          echo "Service URL: $SERVICE_URL"
          echo "url=$SERVICE_URL" >> $GITHUB_OUTPUT
      
      - name: Deployment Summary
        run: |
          echo "✅ Deployment successful!" >> $GITHUB_STEP_SUMMARY
          echo "🌐 Service URL: ${{ steps.get-url.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "📦 Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
